/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPIM_EE.h"
#include "SPIM_EE_PVT.h"
#include "SPIS_HOST.h"
#include "SPIS_HOST_PVT.h"
#include "EE_MISO.h"
#include "EE_MISO_aliases.h"
#include "Control_SELECT_SPI.h"
#include "HOST_MOSI.h"
#include "HOST_MOSI_aliases.h"
#include "EE_SS.h"
#include "EE_SS_aliases.h"
#include "HOST_SS.h"
#include "HOST_SS_aliases.h"
#include "EE_MOSI.h"
#include "EE_MOSI_aliases.h"
#include "EE_CLK.h"
#include "EE_CLK_aliases.h"
#include "HOST_MISO.h"
#include "HOST_MISO_aliases.h"
#include "HOST_CLK.h"
#include "HOST_CLK_aliases.h"
#include "EE_WP.h"
#include "EE_WP_aliases.h"
#include "HOST_WP.h"
#include "HOST_WP_aliases.h"
#include "EE_HOLD.h"
#include "EE_HOLD_aliases.h"
#include "HOST_HOLD.h"
#include "HOST_HOLD_aliases.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "SPIM_EE_IntClock.h"
#include "SPIS_HOST_IntClock.h"
#include "USBUART_Dp.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dm_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

